#!/bin/sh

# Reload environment
source /etc/env

# Get the maximum upload file size for Nginx, default to 1 Meg
USE_NGINX_MAX_UPLOAD=${NGINX_MAX_UPLOAD:-1m}
# Generate Nginx config for maximum upload file size
sed -i "/client_max_body_size\s/c\client_max_body_size $USE_NGINX_MAX_UPLOAD;" /etc/nginx/conf.d/upload.conf

# Get the number of workers for Nginx, default to 1
USE_NGINX_WORKER_PROCESSES=${NGINX_WORKER_PROCESSES:-1}

# Modify the number of worker processes in Nginx config
sed -i "/worker_processes\s/c\worker_processes ${USE_NGINX_WORKER_PROCESSES};" /etc/nginx/nginx.conf

exec /usr/sbin/nginx
